### ISSUE TITLE
Error: failed to call OrtRun(). error code = 6.

### ISSUE THREAD

**Issue by w3cdotorg** [jacoblee93/fully-local-pdf-chatbot#13]
Hi!

Just tried to run this today, by cloning the repo and running:
`$ yarn`

Then:
`$ npm run build`
`$ npx serve@latest out`

When I try embedding a PDF, after a while it just fails with 'An error occurred during model execution: "Error: failed to call OrtRun(). error code = 6.'.

I don't know enough about WASM, or where the error could come from... Ollama is up and running on 127.0.0.1:11435. 

Thanks!

<img width="1469" alt="Screenshot 2024-02-29 at 4 43 00 PM" src="https://github.com/jacoblee93/fully-local-pdf-chatbot/assets/19980081/0ee0eb57-3c85-4666-a28a-469f0ece9569">

**Comment by jacoblee93** [comment]
Hey! Looks like a transformers.js error. You could try switching them out for Ollama-served embeddings now that Nomic is well supported there:

https://js.langchain.com/docs/integrations/text_embedding/ollama

**Comment by w3cdotorg** [comment]
Thanks, I'll try! Do you know if it makes sense to play with the chunk size / chunk overlap?

**Comment by w3cdotorg** [comment]
OK, it works perfectly when switching to the ollama embeddings. Thanks!
