### ISSUE TITLE
Vanilla Javascript example?

### ISSUE THREAD

**Issue by flatsiedatsie** [jacoblee93/fully-local-pdf-chatbot#20]
I'd love to integrate your work into a web project I'm working on. Could you perhaps share a minimal vanilla javascript version of the pure browser-based implementation?

**Comment by jacoblee93** [comment]
The important stuff is in `worker.ts`, it should be pretty easy to just strip the types from there.

**Comment by flatsiedatsie** [comment]
I'm not a professional developer. But I understand that you mean that the 'engine' of the project is the worker.

Would it be possible to only generate the worker somehow? Currently I'm having to search through a lot of files to see if I can extract something that I can then integrate into my own project.

..and unfortunately that project is not generated with NPM, it's just old-school html and JS.
