### ISSUE TITLE
Issues in running the app locally

### ISSUE THREAD

**Issue by jacopo-chevallard** [jacoblee93/fully-local-pdf-chatbot#3]
Hi, first of all thanks for the great app!!  👏👏

I'm trying to run it locally (on my 16GB MacBook Pro), I've installed ollama, loaded Mistral, installed the dependencies (using node v21.1.0) and launched the app on my browser (Chrome version 118.0.5993.70), but I get the following errors

```
kwift.CHROME.js:2 Uncaught (in promise) Error: Extension context invalidated.
    at H (kwift.CHROME.js:2:1075208)
    at n.runtimeSendMessage (kwift.CHROME.js:2:1025148)
    at kwift.CHROME.js:2:895852
    at kwift.CHROME.js:2:1044508
    at o (kwift.CHROME.js:2:1044296)
    at R._logException (kwift.CHROME.js:2:1044500)
    at kwift.CHROME.js:2:905256
```

and

```
models.js:197 An error occurred during model execution: "Error: failed to call OrtRun(). error code = 6.".
```

any idea of what can be causing them?

**Comment by jacoblee93** [comment]
Looks most similar to this:

https://github.com/microsoft/onnxruntime/issues/15683

Are you able to swap out transformers.js for:

https://js.langchain.com/docs/modules/data_connection/text_embedding/integrations/ollama

I can look into adding a mode today if you need help!

**Comment by jacopo-chevallard** [comment]
Thanks for the quick reply! 

By swap transformers.js you mean replacing calls to transformers.js with calls to the library (ollama) you linked?

**Comment by jacoblee93** [comment]
Yes, it should be directly swappable

**Comment by TheScorched** [comment]
Hello. I made the following recommended changes by going to worker.ts and embedding the code from the prescribed link. 

Here is what my new code looks like:

`
import { OllamaEmbeddings } from "langchain/embeddings/ollama";

const embeddings = new OllamaEmbeddings({
  model: "Mistral", // default value
  baseUrl: "http://localhost:11434", // default value
});
`

Now I am getting the following error:

There was an issue embedding your PDF: Request to Ollama server failed: 400 Bad Request.

Any recs/advise?

**Comment by jacoblee93** [comment]
I think it should be lower case `"mistral"`, but also I'm not 100% sure Mistral supports embeddings through Ollama - can you try with `llama2`? 

CC @jmorganca

**Comment by jmorganca** [comment]
Yes it should be lowercase: `mistral`. These should be [case insensitive](https://github.com/jmorganca/ollama/issues/336) soon

**Comment by TheScorched** [comment]
Thanks for the reply. Using "mistral" I'm not getting any errors, however still processing a PDF to prompt so lets see. Will pivot to llama2 if this doesnt prove successful.

**Comment by Janaka-Steph** [comment]
Regarding `An error occurred during model execution: "Error: failed to call OrtRun(). error code = 6.".`, I noticed that I dont get the error with smaller chunks in RecursiveCharacterTextSplitter.

**Comment by Dav1nx1** [comment]
@Janaka-Steph thanks for sharing, works for me your solution.

**Comment by iplayfast** [comment]
@Janaka-Steph Could you put source code of the ollama swap transformers.js up, I've no idea what you guys are talking about.

**Comment by Janaka-Steph** [comment]
@iplayfast I also don't know what you are talking about haha. I just noticed that my little LangChain RAG app gave me the same error, and that problem was fixed by reducing the chunk size.

**Comment by TheScorched** [comment]
@iplayfast these are changes all taking place in the file named, "worker.ts". I believe it lives in the app folder. Once there you'll find the lines that mentions embedding. Replace it with this:

`
import { OllamaEmbeddings } from "langchain/embeddings/ollama";

const embeddings = new OllamaEmbeddings({
model: "mistral", // default value
baseUrl: "http://localhost:11434/", // default value
});
`

You can also ctrl-f to find the chunk size.. Try changing lower and lower until you get it working.

Disclaimer: still not working on my end lol :)

**Comment by jacoblee93** [comment]
What types of machines/OS are you all using?

Also, would suggest using an even numbered version of Node rather than an experimental odd one:

https://stackoverflow.com/questions/74696923/how-to-solve-odd-numbered-node-js-versions-will-not-enter-lts-status-and-should

**Comment by TheScorched** [comment]
Dell i7 | 64gb mem | NVIDIA GPU | Kali Linux

**Comment by jacoblee93** [comment]
Are you on the latest Ollama? And can you call them outside of this app?

I know Linux support was relatively recent

**Comment by KannamSridharKumar** [comment]
I'm quite familiar with python and running ollama locally. 
I'm completely new to npm and yarn. 
I've installed the package using  - yarn add https://github.com/jacoblee93/fully-local-pdf-chatbot.git
Then tried to start the application using - npx serve@latest out
It provided me a local and network serve url. But this is not working. 
Can you please provide me the instructions to install and run the app locally. Sorry for too basic question.

**Comment by jacoblee93** [comment]
yarn add? I don't think I published this to npm so that shouldn't be possible.

Can you give me a bulleted list of commands you ran and compare them to the readme?

**Comment by KannamSridharKumar** [comment]
Thanks Jacob, the README file doesn't have command instructions on how to install and run the app locally. It just says "To run/deploy this yourself, simply fork this repo and install the required dependencies with yarn."

I've run the ollama related commands successfully. 
Then I ran only the below two commands
>> yarn add https://github.com/jacoblee93/fully-local-pdf-chatbot.git
>> npx serve@latest out

Can you please update the README with commands to run the app locally.

**Comment by jacoblee93** [comment]
Ah ok. No, you just clone the repo with `git clone`, then run `yarn` to install deps, then `yarn dev` to start it in dev mode. Yes, I will update the README later today.

**Comment by Rulikkk** [comment]
Don't really understand, but I had to do 

```$ yarn add @langchain/core```

To make `yarn build` work locally

**Comment by jacoblee93** [comment]
Interesting - want to add something to the docs?
