### ISSUE TITLE
Adding OSS license

### ISSUE THREAD

**Issue by silvestriluca** [jacoblee93/fully-local-pdf-chatbot#4]
Hello @jacoblee93 .

Since you are encouraging to fork this project, have you considered to release it under an OSS license?

**Comment by jacoblee93** [comment]
Oh, shoot yeah should do that. Thanks for the reminder

**Comment by jacoblee93** [comment]
Done, thanks!

**Comment by silvestriluca** [comment]
Thank you for the quick reply & commit 👍
