### ISSUE TITLE
Failed to Fetch

### ISSUE THREAD

**Issue by jasonl1994** [jacoblee93/fully-local-pdf-chatbot#9]
Hello, I'm trying to deploy ollama and the app on a clound server. I confirm ollama is installed and can generate output with prompt:
![企业微信截图_1705480834524](https://github.com/jacoblee93/fully-local-pdf-chatbot/assets/25019719/23685f7f-8804-4b7c-b63f-24445a2a68ef)

I start ollama service with this command:
![企业微信截图_17054807963443](https://github.com/jacoblee93/fully-local-pdf-chatbot/assets/25019719/b76ee7c2-bb8c-49d6-9143-36d75abda259)

I start the application by first running
`npm run build`
then
`npx serve@latest out`
I can access the application and see the home page but each time I upload a pdf file, I get following error:
![企业微信截图_17054807213559](https://github.com/jacoblee93/fully-local-pdf-chatbot/assets/25019719/a41dd218-3bda-4db9-a410-516e0ab2acc9)

The clound server is on Ubuntu 22.04.3, with node version 20.11.0 and npm version 10.2.4

Thanks for the help!

**Comment by jasonl1994** [comment]
From what I observed from developer's tool, those returned 404 in the log are actually loaded fine: 
![企业微信截图_17055478056950](https://github.com/jacoblee93/fully-local-pdf-chatbot/assets/25019719/43229b8a-7b12-4367-b648-43470dcf9d06)

I set a breakpoint at the line where the fetch failed, the vairable value passed to the fetch call looks totally correct to me: 
![企业微信截图_17055474552904](https://github.com/jacoblee93/fully-local-pdf-chatbot/assets/25019719/9948a6d4-d61b-4891-b1a0-0ee21493a788)
but the fetch failed anyway:
![image](https://github.com/jacoblee93/fully-local-pdf-chatbot/assets/25019719/1d0ebf57-e314-4d02-b7f0-0575aa8155f1)

**Comment by jacoblee93** [comment]
Is this on a live server? The `OLLAMA_ORIGINS` server needs to match exactly what your live domain is.

I've also just added browser-only mode which doesn't require any CORS setup if that's interesting to you!
